- contributors.md
- paper_teaching-learning-RSE.md
I've written some general introductory text to highlight a bit of history about RSEs and the reasons why the topic that this paper looks at is important.
I've also started adding some relevant references.
I'll aim to do a bit of work on the challenges section next...
> Adding some introductory text to set the scene

- paper_teaching-learning-RSE.md
Opening a draft PR with content for a related work section. This is a work in progress, additional content to be added soon.
> Content for related work section

- paper_teaching-learning-RSE.md
Hi all,
last week we found that most likely a PhD is required for people to become active parts of the research domain and therefore be RSEs that have covered the "R".
Let's discuss here what are your thoughts!
> add a part on a graduation path

- contributors.md
- paper_teaching-learning-RSE.md
Since Helmholtz is one of the largest research organizations in Germany and is quite active in the RSE area, I thought it would be worth mentioning…
> Add paragraph on RSE teaching activities within Helmholtz

- paper_teaching-learning-RSE.md
Hi all,
As discussed today with @jngrad  I'd like to bring the discussion of target audience earlier in the paper.
To make sure it is widely read. I changed the working title slightly to be more bold...
> write sth. on the target audience

- paper_teaching-learning-RSE.md
slight rewording "combinable" licenses
> slight rewording

- paper_teaching-learning-RSE.md
I started to add an overview on the sections for the introduction. 
For the 'Organizational Infrastructures' I did not add anything yet as it was hard to combine the teachers aspect 
with the organizational aspects of acquiring RSE skills
> Started on chapter overview in intro

- paper_teaching-learning-RSE.md
@mhagdorn and @knarrff I tried to find the common ground between your rewording changes. of #54, #47, #50, #51 .
Please have a look that you find your ideas retained.
> 70 merge rewording changes

- paper_teaching-learning-RSE.md
some minor typos found and fixed
> fix some typos

- paper_teaching-learning-RSE.md
I've come up with a new section title for "Current Day Contextualisation" which I hope makes it a little more obvious what this section is about. Also reworded some of the sentences and split them up.
> Reword current day contextualization

- bibliography.bib
- paper_teaching-learning-RSE.md
> add DLR classification

- paper_teaching-learning-RSE.md
Adjust column widths based on text length. Use a more compact layout and slightly increase spacing between rows.
> Make tables more legible

- bibliography.bib
- competencies.md
- institutionalized_education.md
- survey.md
I added a few sentence in the sections mentioned in #110.
They are repetitive and might not need to be included in all four sections.
In the “FAIRness” section, the last addition, the added paragraph contradicts the the previous paragraph which states “Material with rich metadata are indexed in online databases”, which I think overstates the status quo, as the citations mostly mention hand curated lists without sophisticated search facilities (if any).
Resolves #110
> Mention lack of findability of RSE open educational resources

- competencies.md
> 102 remove workshop results section

- contributors.yml
Added another funding source to myself
> add ClCi to MS acknowledgements

- competencies.md
I've added some general background to the abstract to set the scene. I've also expanded RSE to Research Software Engineer in the title. I think it's important to use the expanded term at least in the early stages of the paper since if we're targetting this at a journal, while it will reach some RSEs, it's much more likely to reach a wider section of the research community (and I guess that's our aim anyway) and they may not be familiar with the term RSE or the concept of a Research Software Engineer.
The abstract is now 199 words, I'm guessing for most submissions the abstract limit will be either 150 or 200 words? We may well need to cut this back a bit but I wanted to add something to set the scene at the start.
> Extended the abstract, modified the title

- CONTRIBUTING.md
- README.md
Most of our contributing guides are now diúplicated into a contributing file. Additionally I wrote sth. about contributors and authors.... what do you think about it?
> duplicate contribution guides into a CONTRIBUTING file.

- intro.md
No new content. Just fixing spelling errors in the introduction.
> Fix some spelling errors in chapter 'Introduction'

- competencies.md
Some minor changes I made during reading the entire paper. It is coming together quite nicely. Feel free to cherry-pick.
> various minor changes

- competencies.md
> categorizing of specializations

- bibliography.bib
- competencies.md
- survey.md
Description of changes:
- define OER and provide citations
- continue search for resource directories
> Continue survey of online resources

- competencies.md
- contributors.yml
Maybe this is a bit early in the process, but these are some things that I found irritating on my first read and what I would write instead.
> Some general improvements

- bibliography.bib
- competencies.md
These two refereces would fit in very well.
Slightly related to #135.
Also fixes other missing references.
> add citations

- .github/spellignore.txt
- bibliography.bib
- competencies.md
This PR updates the related work in line with #161. It doesn't currently include details of material from ELIXIR but this is being handled through #15.
> Add related work

- competencies.md
The introduction for the competencies paper is looking great. I've made a number of minor suggested edits and also included some comments in this PR.
> Minor updates to wording in introduction for competencies paper

- .github/spellignore.txt
- .github/workflows/compile.yml
- .github/workflows/spellcheck.yml
- Makefile
- competencies.md
using https://github.com/tomduck/pandoc-xnos
> Add section numbers

- competencies.md
Barely enough, to close the issue.
> work a bit on the comparison with BioExcel such that at the very least, we have a teaser

- competencies.md
Closes #125.
Overview of the part of the [tree](https://www.hpc-certification.org/cs/map/) related to this paper:
> Relate to skills defined by HPCC

- competencies.md
Some minor changes I noticed re-reading the paper in its entirety.
> read-through of paper

- Makefile
- call_to_action.md
- competencies.md
- filter.py
- institutionalised_education.md
- intro.md
- survey.md
- template.py
Description of changes:
- fix sectioning of chapters
- place the acknowledgements before the appendix (fixes #193)
- address regression in non-PDF/A pipeline (see https://github.com/CaptainSifff/paper_teaching-learning-RSE/pull/180#issuecomment-1812504831)
> Improve build pipeline

- bibliography.bib
- competencies.md
going over the future work section i rediscovered the sed still.
I've elaborated that a bit, and added a reference to some DFG rules(Merkblatt Sachbeihilfe)
that should be common enough, so that a lot of people encounter it.
This would close this box for the competencies paper.
> 139 rse certificate for dfg

- competencies.md
Related to #159.
Several nouns were previously capitalized, while others not.
This converts most to lowercase, but keeps some names that refer to the projects and other initiatives from literature as capitalized. These are typically in quotes anyway.
My approach was mostly chaotic and based on quick eye-scan and finding similar entries. Feel free to edit directly, feel free to protest. This is mainly a question of style, and style is sometimes personal.
> Consistent capitalizations

- competencies.md
- contributors.yml
I added my author information, even though I feel like I did not contribute much (like others also already commented). Feel free to accept or reject this PR as need to do what is best for the paper.
> Add guido juckeland to authors

- competencies.md
As discussed in #187 and todays call
we go with the suggestion by Toby.
> Reorder authors

- competencies.md
```diff
- 9 Contribution details
+ Contribution details
```
Similarly to the Acknowledgements. It is a functional part of the manuscript, not a content-related part.
> Make Contribution Details an unnumbered section

- competencies.md
I added a quick definition of researchers. Feel free to comment and expand!
> add a definition for Researchers

- LICENSE.md
> add a license file

- competencies.md
I've put a brief paragraph on the top 5 in the intro of Section 4 (Foundational RSE competencies). I have turned the bullet points in 4.4 (RSE tasks and responsibilities) into paragraphs. I have also rearranged them to follow some order.
> 241 rse tasks and responsiblities section

- .github/spellignore.txt
- bibliography.bib
- competencies.md
> add environmental sustainability section (#247)

- bibliography.bib
- competencies.md
This adds a sentence to the SE skill about awareness of SE methods in PM.
To give an example of a very software specific PM practice the general idea of 
product line management is exemplified in the tasks and responsibilities section.
This is related to #263
> Elaborate on SE project management

- competencies.md
This is a first draft of being more concrete about what we mean by foundational.
It also includes a small outlook into what might come (in very broad terms)
However, in the current structure of the introduction this is a few paragraphs in
but I see no good way to switch the current ones around.
> Specify what we mean by foundational

- .github/spellignore.txt
- bibliography.bib
- competencies.md
Fixes the code analysis tools part of #263
> Add paragraph about code analysis tools

- competencies.md
This nicely mirrors the sentence about domain research
and fixes #260 apart from mentioning `unknown unknowns' somewhere. 
But I think that might fit somewhere more general
and I'm open for ideas there.
> Add sentence about SE research overview

- bibliography.bib
- competencies.md
> Some words that an RSE has a special obligation for making results explainable.

- competencies.md
The point here is: also in other disciplines. All (most of?) the humanities, for example, start to use RS, not just DH.
> do not single out DH

- competencies.md
I have re-read the intro and added some minor changes. I think the most interesting change with some questions attached is 80bd82c, what do we mean with _software skills_? Is it digital skills in general which would include data management or software programming in particular?
> re-read intro

- competencies.md
Not all PIs have the opportunity to give full-sized lectures, e.g., outside of universities. They should be able to do so, and so, they "may" teach.
> teaching should be optional as PI

- competencies.md
Software (including source code) can be generated. This does not need to be generated by AI, other methods exist as well. I would still call these "software".
> Do not limit software to be human-written

- competencies.md
... to those of us without Latin education
> explain lingua franca

- competencies.md
attempt to reword the paragraph on academic diversity #300
> reword G20 #300

- competencies.md
* not all senior people are employed
* basic digital skills are probably operating a web browser or word processor
> replace word

- competencies.md
> mention that training time needs to be given

- .github/workflows/compile.yml
- .gitmodules
- competencies.md
Description of changes:
- add missing fields in incomplete BibTeX records
- fix broken BibTeX records
- point submodule to the GitHub repository, rather than to a local fork
> Finalize bibliography

- competencies.md
move paragraph around and rephrase to reduce repetition
> move categorisation

- .github/workflows/compile.yml
- .gitmodules
> do not put method (https/ssh) into URL for submodule

- competencies.md
> mention that RSEs are mostly self taught in SE

- contributors.yml
With this work ongoing for a long period of time, I have been supported by some different projects that are directly related to the work being done here. I'm adding an additional grant code to acknowledge support from a more recent project.
> Add additional grant code to acknowledgements for JC

- competencies.md
- glossary.tex
Closes #324, trying to distill what was already discussed there and what was discussed in our meeting yesterday.
> Clarify Legacy RSE specialization

- competencies.md
Reverts the-teachingRSE-project/competencies#342
> Revert "Edit some typos and enhance SMP part"

- .github/spellignore.txt
- competencies.md
> Add sentence on maturity assessment to SWLC

- .github/spellignore.txt
- competencies.md
- glossary.tex
> Suggested edits and minor updates from full review of the paper.

- contributors.yml
Gerasimos had a point and we should definitely do it consistently.
> JPT re-add previous affiliation

- competencies.md
First draft for addressing the first checkbox of #341
> Rework par. 5 of introduction

- competencies.md
> Yvgrossmann feedback

- competencies.md
I introduced some more words into the specialization section.
> introduce more additionals

- competencies.md
As suggested in #341 I replaced instruct with the sentence written there.
> Add suggestion to replace instruct

- Makefile
- summarised_competencies.md
This PR attempts to create a shortened separate version of the paper focusing on competencies. The summarised version is located in the file summarised_competencies.md
> Summarised Version

- competencies.md
- summarised_competencies.md
There seems to be no end of minor issues in the main paper - I spotted some more, the first two patches.
I have shortened some of the challenges and added them back in.
> Summary values challenges

- summarised_competencies.md
> remove glossary

- competencies.md
- summarised_competencies.md
I have condensed the paper a little more, especially with reducing the number of references in mind. With PR #375 this should reduce the number of references to 16. We need to remove another 4 references. Maybe merge #375 first and then see if we can identify another 4 candidates for removal. Lengthwise we should be getting there.
Each change (removal) is a separate commit to allow cherry picking.
> 368 further condensation

- competencies.md
- response_to_referees.md
Hi all,
I tried to feed me my workflow and thought I start with something simple. While looking at that indentation I found out, that 5.4.1 is not in the TOC. While looking into that I found out, that our TOC is not generated from the headings. While looking into that, I found out, that the headings are not quite consistently and thoroughly used. 
So now we have a new TOC and consistent use of headings, some automatic links, and a fixed indentation.
I would be grateful, If someone more proficient in MS products could check if I used the track changes feature correctly.
Note to future selfs: I got a warning that the creation of the TOC cannot be put under track changes.
> fix + changelog to indentation in 5.4.1

- competencies.md
- response_to_referees.md
Closes #386, see the `reponse_to_referees.md`.
> Review reaction: Clarify scope

- competencies.md
- response_to_referees.md
marking it draft as it doesn't yet address all of the issues raised by the reviewers.  In particular:
* second item of #388 needs to be dealt with, @hvwaldow might have some suggestions
* second item of #394 needs to be dealt with. I would prefer to keep the grammar as it is but will have to look at the rest of the paper again. Strengthening the ethics section by adding something to the curricula is a good idea
> Mh feedback1 values

- Makefile
- competencies.md
- response_to_referees.md
> Add a subtitle
