the-teachingRSE-project/competencies

paper_teaching-learning-RSE.md
Some parts of the Helmholtz section were no longer readable/understandable as the previous reference identifiers are not shown in LaTeX.
=> fix typos and spell out references

competencies.md, related-work-training.md
This PR restructures and shortens the Related Work section, separating the initiatives that are doing something very related to the core of this paper from the initiatives that implicitly do it by providing teaching material on various topics.
For the latter, I condensed the material into three paragraphs:
- Carpentries and related
- HPC-focused
- Germany-focused
All the original material is copied into a separate file, to be used in a separate publication.
I understand that this will be quite a controversial change, so please help me understand if I misplaced some project. The goal is for the paper to become easier to read and the reader to get faster to the point of the paper.
Related to #166.
Current version rendering:
=> Restructure and shorten the Related Work

.github/spellignore.txt, .gitignore, competencies.md, contributors.yml
This PR changes the order of some paragraphs, merges or partially drop others, and in total shrinks the introduction by 27%, to a bit less than 1.5 pages, including the terminology subsection.
In my view, the flow now makes more sense, the reader gets quicker to the point of the paper, while all (?) original points are maintained. I will annotate specific parts regarding some my motivation, @CaptainSifff please check.
1. Computers are important for research
2. Researchers need more and more computer skills that they don't learn in their studies
3. Researchers write software. RSE is a term and a career option.
4. RSEs are diverse but share core skills. Btw, they also abide to FAIR.
5. This paper identifies values and competencies
6. Context and target audience of this paper
7. Outline (in …
=> Reflow and shorten the introduction

competencies.md
Why are there both?
I understand that there was the intention to discuss in detail what future plans are. In that sense, having a "Future Work" section sounds fine.
But then, there is also "Conclusion and Outlook". The "Outlook" part however is, as I see it, only one sentence.
The easiest "fix" would be to rename the `Conclusion and Outlook` into `Conclusion`.
=> Future Work vs Outlook

competencies.md
Fixes a few inconsistencies.
I have not touched any capitalizations inside the text (e.g., "Machine Learning" vs "machine learning"), these are still inconsistently used. Should I enforce some variant of those as well?
Rendering:
=> Consistently use sentence case in headings

.github/spellignore.txt, competencies.md
Related to #159, mostly tiny things.
Summary:
- digitalization -> digitalisation (the spellchecker did not know about that word)
- license -> licence (yes, [the SSI also uses licence](https://www.software.ac.uk/search/node?keys=licence))
- somma hyphens and commata
Discovered with the help of the amazing (open-source) [LanguageTool](https://languagetool.org/), ignoring many false positives.
@jcohen02 all good?
=> Minor language fixes for British English

competencies.md
Current section name: Required generic RSE skills
Proposed section name: Foundational RSE competencies
Paper title: Foundational Competencies and Responsibilities of a Research Software Engineer
Motivation:
- I think that the "generic" is downplaying the importance of these skills
- "Required" sounds a bit strange and is not really defined who requires them
- Better fit with the paper title
The contrast between "generic" and "special" is explained in the paragraph, but I think it unclear from the top-view.
=> Rename "Required generic RSE skills" section

.github/spellignore.txt, Makefile, competencies.md, glossary.tex
Add a glossary for:
- acronyms (HPC, STEM, FAIR, ...)
- skill codes (DOCBB, SWREPOS, ...)
- technical terms (COBOL, GitHub, SysOp, design pattern, ...)
=> Add glossary

competencies.md
I changed the title to "use software repositories" to delineate them from the domain repos in the research part.
=> make the title of a competency more precise

competencies.md
An attempt to make that paragraph more suited for *4.2. Research Skills*.
+ Starting that paragraph with "FAIR" somehow primes (at least me) for
undestanding "re-use" in the "production sense".
+ I tried to focus this on skills that are *not* necessary for re-use in
traditional SE.
+ The climate model example I was mentioning in the meeting is mentioned here:
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2022MS003588 but I
guess that is too esoteric to mention it in the SRU paragraph.
+ The bit about "software citation and metadata skills" is redundant because
that is also mentioned in \skillsection{SP}.
=> rewrote \skillsection{SRU}

.github/spellignore.txt, bibliography.bib, competencies.md
Resolves #58 by adding a sentence to DOCBB, refering to the Diátaxis framework.
As I mentioned in the linked issue, I would like to add mention of how this relates to some of the other skills. But happy to let that go if others prefer to keep this minimal.
=> Refer to Diátaxis framework in DOCBB

bibliography.bib, competencies.md, glossary.tex
the latest Code for Thought [episode](https://codeforthought.buzzsprout.com/1326658/14838208-en-make-computing-greener-loic-lannelongue) contains a very interesting interview on the GREENER principles. This looks like an excellent starting point for exploring environmentally sustainable research computing. Added sentence and link to paper.
=> add GREENER principles

competencies.md, glossary.tex
This fixes #259 by introducing UML as a current tool for modeling and also communicating and documenting software design and structure.
As it also helps with forming an actual formalised model of the software I added brackets around `mental' in MOD.
=> Add paragraph about UML in T&R

.gitmodules
do not put method (https/ssh) into URL for submodule; use relative path instead which will choose the method used for the main repo
=> do not put method (https/ssh) into URL for submodule

competencies.md
The old version said things in a roundabout way, doubling things. This is shorter and, I hope, still says the same.
=> rephrase: shorten

.github/spellignore.txt, competencies.md
In the tables in 5.3, so far we often use 'developer', while we really do not only mean 'developing', but also all other activities by an RSE. This PR changes 'developer' to 'RSE' in cases where this is in the above sense.
=> avoid 'SW developer', use RSE instead

contributors.yml
When I first joined (September 2023), and till March 2024, I was employed by the Technical University of Munich.
Since April 2024, I am employed by the University of Stuttgart.
Since there are significant time intervals in both universities, I feel like both should be listed here.
The pagination was already broken before, and I think we should not worry about it outside the published versions. For the arXiv preprint, we can still work around with the margins, if we want to keep the keywords in the first page. For the peer-reviewed version, there will anyway be a different template.
We could also drop the specific institutes (e.g., me and @jngrad are now in different institutes in the same university) and merge the affiliations at the universities/organizations level.
=> Update affiliation GC

competencies.md
Follow-up of #330.
- Removes the "brought into" connotation in the first use
- Clarifies that it can change later on, in the appendix
=> Clarify home domain

competencies.md
Related to #356 (more might come at the end of the manuscript, after merging #350).
We don't explicitly call `\maketitle` anywhere (pandoc does this for us), so changing the margins specifically for the titlepage is... complicated. My hacky solution was to set the general geometry to what we want the title page to have, and then update the geometry in the main content.
=> Fit title page in one page

competencies.md
Touching this, a question would be whether we really want to have this and the `Terminology` as different sections at the same level. I would suggest:
- Terminology
- The term Research Software Engineering
- Other terms 
@CaptainSifff @jpthiele opinions?
=> Merge terminology sections into one larger section

.github/spellignore.txt, acknowledgements.md, competencies.md, contributors.yml, filter.py
Oh well, I looked into the Credit system again, and I only thought....
Well, how  does this fit to us?
So I wrote a generic text to tick that box, and went on to detail those parts that I could remember, which you have contributed over the past years.
Feel free to raise your opinions.
I also accept private E-Mail, if I took a wrong direction somewhere....
Now comes the pleasure of finding all your github usernames ....
=> Rework contribution section

.gitignore, contributors.yml, summarised_competencies.md
In the `summarized_competencies.md`:
- Removes the duplicate commented-out list of authors (the comment needs to be in YAML anyway)
- Replaces "University of Würzburg" with `https://github.com/the-teachingRSE-project` as affiliation.
- Fix an assertion regarding the initials not appearing in the acknowledgments list (replaces it with `We`, renders normally)
- Update the `.gitignore`
Motivated by the CI failing for the pull request #362 (not for the branch, but for the merged result).
=> Fix summarised_competencies CI issues

.github/workflows/compile.yml
Our CI is based on `ubuntu-latest`. I assume this was recently switched to Ubuntu 24.04, which does not allow pip installations outside a virtual environment.
This creates a venv before installing the Python requirements.
=> Fix CI: Create a Python venv

summarised_competencies.md
Related to #368. I tried to condense everything that was too verbose or a side-story, and to remove anything related to the removed part (career levels, organizational support, etc). I also removed all but one placeholders for further publications, as I don't see that happening before the end of the month.
Starting point:
- Introduction: 1026 words
- Terminology - RSE: 299 words
- Terminology - further: 214 words
- **Total:** 1539 words
Result:
- Introduction: 506 words (50% or original)
- Terminology - RSE: 0 words (0%) - I think this is one of the verbose parts that should not really be part of this particular paper, since there are already so many others working on the definition.
- Terminology - further: 273 words (128%)
- **Total:** 779 words (51% of original)
Introduction: …
=> Summary of the introduction

summarised_competencies.md
Considering this section without , the `wc' utility would count 1422 words before this commit and 685 after (737 fewer).
Removed references to @Nieva2020 and @SSIDataScience from the text (these were the only ones(. Kept references to @GDPR, @ExportControl, @FAIR.
I did not make items out of the subsections; this may still be done.
This is for issue #374 aka
https://github.com/the-teachingRSE-project/competencies/issues/374
aka "Condensed Version of Specializations Section".
=> Summarized '#sec:rse-specialisations'

contributors.yml, filter.py
Add rewriting authors information into an existing CITATION.cff file. For this to work, a CITATION.cff file needs to already exist. filter.py can then rewrite the authors block according to the contributor list. The rest of the file remains the same (needs to be specified someplace else, ideally, beforehand).
=> add CITATION.cff rewriting
